#!/bin/sh

if [ $# != 1 ]; then
    echo "USAGE:    $0 tag"
    exit 1
fi

set -x

git pull origin master
git pull --tags
git checkout $1
git status

lein do fgoc -f, midje

head -2 project.clj
git log | head
read -p "<ENTER> to deploy, or <CTRL>-C to abort" dummy
lein deploy clojars

